version: '2'
services:
  log:
    build:
      context: ../../
      dockerfile: make/dev/container/log/Dockerfile
    image: dev_log:dev
    restart: always
    volumes:
      - /var/log/board/:/var/log/docker/
    networks:
      - board
    ports:
      - 1514:514
  db:
    build: 
      context: ../../
      dockerfile: make/dev/container/db/Dockerfile
    image: dev_db:dev
    restart: always
    volumes:
      - /data/board/database:/var/lib/mysql
    env_file:
      - ../config/db/env
    networks:
      - board
    ports:
      - 3306:3306
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "db"
  gogits:
    build:
      context: ../../
      dockerfile: make/dev/container/gogits/Dockerfile
    image: dev_gogits:dev
    restart: always
    env_file:
      - ../config/gogits/env
    volumes:
      - ../config/gogits/conf/app.ini:/tmp/conf/app.ini
      - /data/board/gogits:/data:rw
    ports:
      - "10022:22"
      - "10080:3000"
    networks:
      - board  
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "gogits"
  jenkins:
    build:
      context: ../../
      dockerfile: make/dev/container/jenkins/Dockerfile
    image: dev_jenkins:dev
    restart: always
    networks:
      - board
    volumes:
      - /data/board/jenkins_home:/var/jenkins_home
      - ../config/ssh_keys:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    env_file:
      - ../config/jenkins/env
    ports:
      - 8888:8080
      - 50000:50000
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jenkins"
  apiserver:
    build:
      context: ../../
      dockerfile: make/dev/container/apiserver/Dockerfile
    image: dev_apiserver:dev
    restart: always
    volumes:
      - ../../tools/swagger/vendors/swagger-ui-2.1.4/dist:/go/bin/swagger:z
      - /data/board/repos:/repos:rw
      - /data/board/keys:/keys:rw
    env_file:
      - ../config/apiserver/env
    networks:
      - board
    links:
      - db
    ports: 
      - 8088:8088
    depends_on:
      - log
      - jenkins
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "apiserver"
  tokenserver:
    build:
      context: ../../
      dockerfile: make/dev/container/tokenserver/Dockerfile
    image: dev_tokenserver:dev
    env_file:
      - ../config/tokenserver/env
    restart: always
    networks:
      - board
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "tokenserver"
  collector:
    build:
      context: ../../
      dockerfile: make/dev/container/collector/Dockerfile
    image: dev_collector:dev
    restart: always
    env_file:
      - ../config/collector/env
    networks:
      - board
    links:
      - db
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "collector" 
  proxy:
    build:
      context: ../../
      dockerfile: make/dev/container/proxy/Dockerfile
    image: dev_proxy:dev
    networks:
      - board
    restart: always
    volumes:
      - ../config/proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - ../../src/ui/dist:/usr/share/nginx/html:z
    ports: 
      - 80:80
    links:
      - apiserver
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
  grafana:
    build:
      context: ../../
      dockerfile: make/dev/container/grafana/Dockerfile
    image: dev_grafana:dev
    restart: always
    volumes:
      - /data/board/grafana/lib:/var/lib/grafana
      - /data/board/grafana/log:/var/log/grafana
      - ../config/grafana:/etc/grafana/config
    networks:
      - board
    ports:
      - 3000:3000
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "grafana"
  graphite:
    build:
      context: ../../
      dockerfile: make/dev/container/graphite/Dockerfile
    image: dev_graphite:dev
    restart: always
    networks:
      - board
    ports:
      - "2003:2003"
    depends_on:
      - log
    volumes:
      - /data/board/graphite/storage/whisper:/opt/graphite/storage/whisper
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "graphite"
  elasticsearch:
    build:
      context: ../../
      dockerfile: make/dev/container/elasticsearch/Dockerfile
    image: dev_elasticsearch:dev
    restart: always
    env_file:
      - ../config/elasticsearch/env
    networks:
      - board
    ports:
      - 9200:9200
    depends_on:
      - log
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/board/elasticsearch:/usr/share/elasticsearch/data
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "elasticsearch"
  kibana:
    build:
      context: ../../
      dockerfile: make/dev/container/kibana/Dockerfile
    image: dev_kibana:dev
    restart: always
    networks:
      - board
    depends_on:
      - log
    volumes:
      - ../config/kibana:/config
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "kibana"
networks:
  board:
    external: false