version: '2'
services:
  log:
    build:
      context: ../../
      dockerfile: make/dev/container/log/Dockerfile
    image: dev_log:dev
    restart: always
    volumes:
      - /var/log/board/:/var/log/docker/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - board
    ports:
      - 1514:514
  db:
    build: 
      context: ../../
      dockerfile: make/dev/container/db/Dockerfile
    image: dev_db:dev
    restart: always
    volumes:
      - /data/board/database:/var/lib/mysql
      - ../config/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../config/db/env
    networks:
      - board
    ports:
      - 3306:3306
    depends_on:
      - log
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "db"
  apiserver:
    build:
      context: ../../
      dockerfile: make/dev/container/apiserver/Dockerfile
    image: dev_apiserver:dev
    restart: always
    volumes:
      - ../../tools/swagger/vendors/swagger-ui-2.1.4/dist:/go/bin/swagger:z
      - /data/board/cert:/cert:rw
      - /etc/board/cert:/etc/board/cert:rw
      - ../config/apiserver/kubeconfig:/root/kubeconfig
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../config/apiserver/env
    networks:
      - board
    links:
      - db
    ports: 
      - 8088:8088
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "apiserver"
  tokenserver:
    build:
      context: ../../
      dockerfile: make/dev/container/tokenserver/Dockerfile
    image: dev_tokenserver:dev
    env_file:
      - ../config/tokenserver/env
    restart: always
    networks:
      - board
    depends_on:
      - log
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "tokenserver"
  proxy:
    build:
      context: ../../
      dockerfile: make/dev/container/proxy/Dockerfile
    image: dev_proxy:dev
    networks:
      - board
    restart: always
    volumes:
      - ../config/proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - ../../src/ui/dist:/usr/share/nginx/html:z
      - /data/board/cert/proxy.pem:/etc/ssl/certs/proxy.pem:z
      - /data/board/cert/proxy-key.pem:/etc/ssl/certs/proxy-key.pem:z      
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 80:80
      - 8080:8080
      - 443:443
    links:
      - apiserver
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
  grafana:
    build:
      context: ../../
      dockerfile: make/dev/container/grafana/Dockerfile
    image: dev_grafana:dev
    restart: always
    volumes:
      - /data/board/grafana/data:/var/lib/grafana
      - /data/board/grafana/log:/var/log/grafana
      - ../config/grafana:/etc/grafana/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - board
    ports:
      - 3000:3000
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "grafana"
  elasticsearch:
    build:
      context: ../../
      dockerfile: make/dev/container/elasticsearch/Dockerfile
    image: dev_elasticsearch:dev
    restart: always
    env_file:
      - ../config/elasticsearch/env
    networks:
      - board
    ports:
      - 9200:9200
    depends_on:
      - log
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /data/board/elasticsearch:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "elasticsearch"
  kibana:
    build:
      context: ../../
      dockerfile: make/dev/container/kibana/Dockerfile
    image: dev_kibana:dev
    restart: always
    env_file:
      - ../config/kibana/env
    networks:
      - board
    depends_on:
      - log
    volumes:
      - ../config/kibana:/config
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "kibana"
  chartmuseum:
    build:
      context: ../../
      dockerfile: make/dev/container/chartmuseum/Dockerfile
    image: dev_chartmuseum:dev
    restart: always
    networks:
      - board
    ports:
      - 8089:8080
    depends_on:
      - log
    volumes:
      - /data/board/chartmuseum:/storage
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "chartmuseum"
  prometheus:
    build:
      context: ../../
      dockerfile: make/dev/container/prometheus/Dockerfile
    image: dev_prometheus:dev
    restart: always
    networks:
      - board
    ports:
      - 9090:9090
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "prometheus"
networks:
  board:
    external: true
