version: '2'
services:
  uibuilder-mips7.1:
    build:
      context: ../../
      dockerfile: make/dev/container/uibuilder/Dockerfile.mips
    image: inspursoft/uibuilder-mips7.1
    volumes:
      - ../../src/ui:/board_src
    environment:
       MODE: build
    entrypoint:
      - /entrypoint.sh
