version: '2'
services:
  log:
    build:
      context: ../../
      dockerfile: make/dev/container/log/Dockerfile.mips
    image: dev_log:dev
    restart: always
    volumes:
      - /var/log/board/:/var/log/docker/
      - /etc/localtime:/etc/localtime:ro
    networks:
      - board
    ports:
      - 1514:514
  db:
    build: 
      context: ../../
      dockerfile: make/dev/container/db/Dockerfile.mips
    image: dev_db:dev
    restart: always
    volumes:
      - /data/board/database:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../config/db/env
    networks:
      - board
    ports:
      - 3306:3306
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "db"
  apiserver:
    build:
      context: ../../
      dockerfile: make/dev/container/apiserver/Dockerfile.mips
    image: dev_apiserver:dev
    restart: always
    volumes:
      - ../../tools/swagger/vendors/swagger-ui-2.1.4/dist:/go/bin/swagger:z
      - /data/board/cert:/cert:rw
      - /etc/board/cert:/etc/board/cert:rw
      - ../config/apiserver/kubeconfig:/root/kubeconfig
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../config/apiserver/env
    networks:
      - board
    links:
      - db
    ports: 
      - 8088:8088
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "apiserver"
  tokenserver:
    build:
      context: ../../
      dockerfile: make/dev/container/tokenserver/Dockerfile.mips
    image: dev_tokenserver:dev
    env_file:
      - ../config/tokenserver/env
    restart: always
    networks:
      - board
    depends_on:
      - log
    volumes:
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "tokenserver"
  proxy:
    build:
      context: ../../
      dockerfile: make/dev/container/proxy/Dockerfile.mips
    image: dev_proxy:dev
    networks:
      - board
    restart: always
    volumes:
      - ../config/proxy/nginx.conf:/etc/nginx/nginx.conf:z
      - ../../src/ui/dist:/usr/share/nginx/html:z
      - /etc/localtime:/etc/localtime:ro
    ports: 
      - 80:80
      - 8080:8080
    links:
      - apiserver
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
  prometheus:
    build:
      context: ../../
      dockerfile: make/dev/container/prometheus/Dockerfile
    image: dev_prometheus:dev
    restart: always
    networks:
      - board
    ports:
      - 9090:9090
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "prometheus"
networks:
  board:
    external: true
