version: '2'
services:
  uibuilder7.3:
    build:
      context: ../../
      dockerfile: make/dev/container/uibuilder/Dockerfile
    image: 10.111.25.119/board/dev_uibuilder:7.3
    volumes:
      - ../../src/ui:/board_src
    environment:
       MODE: prod
    entrypoint:
      - /entrypoint.sh
