version: '2'
services:
  uibuilder7.2:
    build:
      context: ../../
      dockerfile: make/dev/container/uibuilder/Dockerfile.arm64v8
    image: inspursoft/uibuilder-arm64v8:7.2
    volumes:
      - ../../src/ui:/board_src
    environment:
      MODE: prod
    entrypoint:
      - /entrypoint.sh
